# Singular Value Decomposition (SVD)

Singular Value Decomposition (SVD) merupakan sebuah metode komputasi untuk membongkar satu matriks utuh menjadi tiga bagian matriks penyusun. Pendekatan ini sangat bermanfaat untuk menganalisis struktur fundamental dari sebuah data dan melihat komponen mana yang paling mendominasi.

Sebagai contoh nyata dalam kompresi gambar, SVD bekerja dengan cara mengisolasi elemen visual utama dari detail-detail minor atau derau (noise). Dengan mengabaikan elemen yang kurang krusial tersebut, kita dapat menekan ukuran file secara signifikan untuk efisiensi penyimpanan, namun tetap mempertahankan kualitas gambar yang proporsional.

### Formulasi Matematis

Sebuah matriks $A$ dengan dimensi $m \times n$ dapat difaktorkan melalui persamaan berikut:
$$A = U \Sigma V^T$$

Berikut adalah rincian fungsional dari ketiga komponen matriks tersebut:
- **Matriks Ortogonal ($U$)**
Matriks ini memiliki dimensi $m \times m$ dan memuat sekumpulan vektor yang disebut sebagai vektor singular kiri. Karakteristik utama dari matriks ini adalah sifat ortogonalnya, yang dapat dibuktikan melalui persamaan $U^T U = I$.

- **Matriks Diagonal ($\Sigma$)**
Matriks berdimensi $m \times n$ ini mendistribusikan nilainya hanya pada garis diagonal utama. Angka-angka ini disebut sebagai nilai singular ($\sigma_i$) dan selalu tersusun dari nilai yang paling besar hingga yang paling kecil ($\sigma_1 \ge \sigma_2 \ge \dots \ge 0$). Besaran nilai singular ini sangat penting karena merepresentasikan seberapa kuat informasi yang dibawa oleh komponen tersebut bagi keseluruhan data.


- **Matriks Ortogonal Transpose ($V^T$)**
Ini merupakan bentuk transpose dari matriks ortogonal $V$ yang berdimensi $n \times n$. Mirip dengan $U$, matriks ini juga mempertahankan sifat ortogonalitas $V^T V = I$, dan elemen-elemen di dalamnya dikenal sebagai vektor singular kanan.


### Interpretasi Transformasi

Proses pemfaktoran ini menunjukkan bahwa transformasi matriks apa pun pada dasarnya adalah serangkaian operasi ruang yang sangat terstruktur. Jika diurutkan, prosesnya berjalan dalam tiga tahap:
- Penyesuaian orientasi awal ruang data menggunakan matriks $V^T$.
- Peregangan atau penyusutan skala ruang data tersebut untuk menyesuaikan bobot informasi menggunakan matriks $\Sigma$.
- Pemutaran akhir orientasi data ke dalam ruang dimensi yang baru menggunakan matriks $U$.

Sifat matematis ini memastikan bahwa matriks asli selalu dapat disusun atau direkonstruksi kembali secara presisi dari ketiga komponen tersebut.

### Kesimpulan

Singular Value Decomposition memberikan jalan keluar yang elegan untuk memahami jeroan dari sebuah kumpulan data. Dengan memilah data berdasarkan nilai singularnya ($\Sigma$), kita memiliki kendali penuh untuk menentukan seberapa banyak informasi yang ingin dipertahankan atau dibuang. Hal inilah yang menjadikan SVD sebagai pondasi kokoh untuk berbagai teknik kompresi dan peringkasan data modern di ranah machine learning.



In [3]:
import numpy as np

np.set_printoptions(suppress=True, precision=4)

A = np.array([
    [7, 3, 8],
    [1, 6, 4],
    [9, 2, 5]
])

U, S, VT = np.linalg.svd(A)

print("Matriks Ortogonal (U):")
print(U)

print("\nNilai Singular:")
print(S)

print("\nMatriks Ortogonal Transpose (V^T):")
print(VT)

Sigma = np.diag(S)

print("\nMatriks Diagonal (Sigma):")
print(Sigma)

A_rekonstruksi = U @ Sigma @ VT

print("\nHasil Rekonstruksi Matriks:")
print(np.round(A_rekonstruksi).astype(int))

Matriks Ortogonal (U):
[[-0.6934 -0.0003 -0.7205]
 [-0.3338 -0.886   0.3217]
 [-0.6385  0.4636  0.6143]]

Nilai Singular:
[15.8054  5.6185  1.9031]

Matriks Ortogonal Transpose (V^T):
[[-0.6918 -0.3391 -0.6375]
 [ 0.5845 -0.7813 -0.2187]
 [ 0.4239  0.5239 -0.7388]]

Matriks Diagonal (Sigma):
[[15.8054  0.      0.    ]
 [ 0.      5.6185  0.    ]
 [ 0.      0.      1.9031]]

Hasil Rekonstruksi Matriks:
[[7 3 8]
 [1 6 4]
 [9 2 5]]
